# Generated by Django 3.1.1 on 2020-09-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudenTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firedrillnumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
