# Generated by Django 3.1.1 on 2020-09-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudenTracker', '0002_student_firedrillnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudenTracker.classroom')),
            ],
        ),
    ]
