# Generated by Django 3.1.1 on 2020-09-20 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudenTracker', '0003_assinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinment',
            name='description',
            field=models.TextField(default='Des'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinment',
            name='duedate',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
