# Generated by Django 3.1.1 on 2020-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudenTracker', '0006_auto_20200920_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='work',
            field=models.ManyToManyField(blank=True, null=True, to='StudenTracker.Assignment'),
        ),
    ]
